### PR TITLE
Correct and improve git clone

### PR DESCRIPTION
**Pull request by Natenom**
correct git glone command and use https instead of git protocol for cloning

### CODE REVIEW

**Comment by tobst** [comment]
Is https an improvement over git@github.com?

**Comment by boldt** [comment]
The recommendation by github changed from time to time:

https://stackoverflow.com/a/11041782

Nowadays, github says: 

> **Cloning with HTTPS URLs (recommended)**
> [...] These URLs work even if you are behind a firewall or proxy
> [...] Git will ask for your GitHub username and password



https://help.github.com/en/github/using-git/which-remote-url-should-i-use

I personally would always use the Git-/SSH-Protocol.

**Comment by opatut** [comment]
It works for non-authenticated users. You don't need an account and upload your ssh public key to github. Since the project is public anyway and this is about installing it, it should probably use HTTPS.

**Comment by opatut** [comment]
Whelp, it's an  outdated URL now anyway :D

**Pull request closed without merging**
