### PR TITLE
Support OBS-lite variant

### PR DESCRIPTION
**Pull request by amandel**
See https://github.com/openbikesensor/OpenBikeSensor_PCB_Board/tree/obs-lite

- [x] Detect OBS-lite variant via VoltageMeter -> GND
- [x] Be relaxed is hardware is not found in OBS lite mode
- [ ] Remove / hide features not supported in OBS lite
- [ ] ...

### CODE REVIEW

**Comment by amandel** [comment]
@opatut  - this version should be ready to run on OBS-lite. 
For now OBS-lite has 
- no / fixed config
- distance offset is fixed 0 
- name is derived from mac address OpenBikeSensor-lite-XXXX
- formal reporting is only via BLE (sorry). You can use nRF Connect or hopefully the upcoming SimRa Android version to receive the data
- serial is today used for debug output only
- detection of the variant is via GPIO 34 which must be pulled to GND

**Comment by opatut** [comment]
Awesome, just a two days ago I received the 0.1.1 PCB and today I'm going to solder it and try it out.

We should talk about serial output some time. I would suggest trying out protobuf as a platform for generating a binary protocol that can efficiently (within the limits of a background Android app, for example) be streamed, parsed, stored and so on. It should be rather easy to use on the embedded device, as it compiles to C++. We could have a "debug" message type as well, and a tiny python script to read your serial output for debug messages and output them as text on the command line, to help with development ;)

**Comment by amandel** [comment]
Cool, happy to get feedback. My test setup is mostly a classical OpenBikeSensor, I hope I did not miss side effects of not available hardware.

**Comment by amandel** [comment]
obs lite has a own firmware

**Pull request closed without merging**
